language: python

services:
  - docker

before_install:
  - docker build -t myimage .
  - docker run -d --name mycontainer -p 80:80 myimage
  - docker ps -a

script:
  - pip install requests
  - python test.py

